### ISSUE TITLE
Another version bump to suit phoenix 1.7.12

### ISSUE THREAD

**Issue by camstuart** [launchscout/live_elements#5]
Look like the live_elements deps need a bump to suit the latest live view.

I'm happy to do a PR if you would like to give me an over view of whats required / how to test

**Comment by superchris** [comment]
Hey currently I'm keeping tests for live_elements in a separate project: https://github.com/launchscout/live_elements_testbed. I updated phoenix and live_view to the latest version and ran the tests without issue. Can you describe what you errors you are getting?

**Comment by camstuart** [comment]
Mix complaints:

mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.124s
Because your app depends on live_elements ~> 0.1.0 which depends on phoenix_live_view ~> 0.18.15, phoenix_live_view ~> 0.18.15 is required.
So, because your app depends on phoenix_live_view ~> 0.20.2, version solving failed.
** (Mix) Hex dependency resolution failed

**Comment by superchris** [comment]
Did you try with live_elements 0.2.1? That's the latest version where I relaxed these constraints.

**Comment by camstuart** [comment]
Thanks Chris!

My mistake, I had just copied this:

```elixir
def deps do
  [
    {:live_elements, "~> 0.1.0"}
  ]
end
```

From: https://hexdocs.pm/live_elements/readme.html#install-hex-package 

But your README is up to date, so not sure sure why the hex docs are not.

Thanks again

**Comment by superchris** [comment]
Hey Cam, I just updated the README, so that change didn't make into the hex release. I may drop another release to fix README so it doesn't confuse people. Thanks for letting me know!

**Comment by camstuart** [comment]
No worries, thanks for building a great lib and your talk on it. Made my life easier!
